version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:8.0-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    secrets:
      - mysql_root_password
      - mysql_password
    volumes:
      - mysql:/var/lib/mysql

  # First WordPress Instance
  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - 81:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    secrets:
      - wordpress_db_password

  # Second WordPress Instance
  wordpress2:
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - 82:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    secrets:
      - wordpress_db_password

  # Nginx Load Balancer
  load_balancer:
    depends_on:
      - wordpress
      - wordpress2
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=wordpress.com
      - NGINX_PORT=80

secrets:
  # MySQL Root Password Secret
  mysql_root_password:
    file: .env
    name:  mysql_root_password


  # MySQL Password Secret
  mysql_password:
    file: .env
    name:  mysql_password


  # WordPress Database Password Secret
  wordpress_db_password:
    file: .env
    name:  wordpress_db_password

volumes:
  # MySQL Data Volume
  mysql:

  # WordPress Data Volume
  wordpress:

  # Nginx Templates Volume
  nginx.conf: